// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VTS.Backend.Infrastructure.Persistence;

namespace VTS.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VtsDbContext))]
    [Migration("20211215204645_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("VTS.Backend.Core.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(DATETIME('now'))");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id", "SerialNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VTS.Backend.Core.Domain.Entities.VehiclePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("VehilceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VehilceId");

                    b.ToTable("VehiclePositions");
                });

            modelBuilder.Entity("VTS.Backend.Core.Domain.Entities.VehiclePosition", b =>
                {
                    b.HasOne("VTS.Backend.Core.Domain.Entities.Vehicle", "Vehilce")
                        .WithMany("Positions")
                        .HasForeignKey("VehilceId");

                    b.Navigation("Vehilce");
                });

            modelBuilder.Entity("VTS.Backend.Core.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
